"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import oauth2_provider

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#Tạo thư mục media để lưu file ảnh

MEDIA_ROOT = '%s/apartment/static/' % BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&50v86qw!i0=7i)8nlf7vno-6b9p1ef)=pf7)w-h%butz1_inu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
#
#
# ALLOWED_HOSTS = [
#     'https://3e4f-2402-800-63b8-91cf-a8cd-6b46-ec92-8ec6.ngrok-free.app',
#     'localhost',
#     '127.0.0.1'
# ]
ALLOWED_HOSTS = ['*', 'localhost', '127.0.0.1', '.ngrok-free.app']


MOCK_MOMO_REDIRECT_URL = 'http://your-frontend-url/payment/result'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apartment.apps.ApartmentConfig',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider',
    'corsheaders',
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.github',
    

    
    

]
DEBUG = True

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True

# If you want to be more specific with origins:
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:19006",
    "exp://localhost:19000",  # For Expo development
    "http://localhost",
    "http://127.0.0.1",
    "https://*.ngrok-free.app",
    "https://*.ngrok.io",
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Thêm whitenoise middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#Database trên PythonAnywhere
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'apartment_db',
        'USER': 'root',
        'PASSWORD': 'Admin@123',
        'HOST': '', #port mặc định của local host
        'PORT': '',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'bethuandethuong$thuan_apartments_db',
#         'USER': 'bethuandethuong',
#         'PASSWORD': 'thuan@04012004Ab',
#         'HOST': 'bethuandethuong.mysql.pythonanywhere-services.com',
#         'PORT': '',
#     }
# }

#Setting cho Cloudinary
import cloudinary
import cloudinary.uploader
from cloudinary.utils import cloudinary_url

# Configuration       
cloudinary.config( 
    cloud_name = "dg5ts9slf", 
    api_key = "523315624128241", 
    api_secret = "kpR83NbacJprFxwz2jCGxt3nb4E", # Click 'View API Keys' above to copy your API secret
    secure=True
)

#react native gọi api login bằng json
OAUTH2_PROVIDER = {
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.OAuthLibCore',
    'ACCESS_TOKEN_EXPIRE_SECONDS': 36000,  # Thời gian hết hạn token
}

CLIENT_ID = '3RmrCK0lxzpRS8E877xpVwfwq3LahldYvHnw3X6x'
CLIENT_SECRET = 'Z2kPsxPENT0qo8zUSXTJjhTtplJw3glH98BnB13FcxHOk92AmgRK5BeG0Zk5R6qRs6peFcX4JuS8kOfrlEB1BPCVGf363XALUEMrnx4ppfa0SrdZk0fOf3Vmrm8HAJlH'
    
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

#Xác thực đăng nhập bằng social account
# AUTHENTICATION_BACKENDS = [
    
#     'allauth.account.auth_backends.AuthennticationBackend', #allauth backend
    
# ]

#Chứng thực user

AUTH_USER_MODEL = 'apartment.User'

#CKeditor
CKEDITOR_UPLOAD_PATH = "ckeditor/pay/"

#driver kết nối với database

import pymysql
pymysql.install_as_MySQLdb()

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files config
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

import os
from dotenv import load_dotenv

load_dotenv()
VNPAY_CONFIG = {
    "vnp_TmnCode": os.getenv("VNP_TMNCODE"),
    "vnp_HashSecret": os.getenv("VNP_HASHSECRET"),
    "vnp_Url": os.getenv("VNP_URL"),
    "vnp_ReturnUrl": os.getenv("VNP_RETURNURL"),
}
TWILIO_ACCOUNT_SID = 'ACe5ceccecadf9bb7905c481db8c24c5bf'
TWILIO_AUTH_TOKEN = 'bea7072084285a5446b71326d05b5de9'
TWILIO_PHONE_NUMBER = '+19786432877'


# VNPAY_CONFIG = {
import os
from dotenv import load_dotenv

load_dotenv()
VNPAY_CONFIG = {
    "vnp_TmnCode": os.getenv("VNP_TMNCODE"),
    "vnp_HashSecret": os.getenv("VNP_HASHSECRET"),
    "vnp_Url": os.getenv("VNP_URL"),
    "vnp_ReturnUrl": os.getenv("VNP_RETURNURL"),
}


MOCK_MOMO_REDIRECT_URL = "http://thuannguyen.pythonanywhere.com/bills/mock-momo/success/"
MOCK_MOMO_IPN_URL = "http://nguyennguyen.pythonanywhere.com/bills/mock-momo/webhook/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-autos-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CLIENT_ID = 'NkMjZTSBUvor7dOEN1AAeTvPkioq2ZoBQYqfqrTx'
# CLIENT_SECRET = 'cQq1QDZzBJOYi5pYitjQ2EMGGITqqaVJEVJrCSabQ6TrPMyBhqYPzUdJMHzWYeYAZNx1NuY1bCYWST3LlWoGA298EMwQAlMtEIehlWIlI5dNbcz6yjXNi16bDxbiuCZM'

CLIENT_ID = 'PZFzK1dtx7zrnoPCbJzxFZTJzSeG06tPf1nbl20f'
CLIENT_SECRET = 'weMx3lDBNBcVgTHPQvlKlOy0bYpieeTBjDXVJBN8NfWXPVMFSv2Z8bRGd96aVqz0zTcGHhvh4vt9YZblo6pab9jxhgXI0hGn3R0yDngHEYB84c4I6rIThdVWBfO5niwO'

