# Generated by Django 5.1.7 on 2025-04-03 10:42

import ckeditor.fields
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('number', models.CharField(max_length=10, null=True, unique=True)),
                ('floor', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('role', models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('RESIDENT', 'Cư dân')], default='RESIDENT', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('apartment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartment.apartment')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255, null=True)),
                ('payment_method', models.CharField(choices=[('momo_tranfer', 'Chuyển khoản Momo'), ('online', 'Thanh toán trực tuyến')], max_length=50)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='pay/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('content', ckeditor.fields.RichTextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ nhận'), ('received', 'Đã nhận')], default='pending', max_length=10)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('relative_name', models.CharField(max_length=100)),
                ('card_code', models.CharField(max_length=15, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelativeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('name', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=20)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('title', models.CharField(max_length=100)),
                ('choice', models.CharField(choices=[('Hygiene_issues', 'Vệ sinh'), ('Facilities ', 'Cơ sở vật chất'), ('Service', 'Dịch vụ')], default='Service', max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('answer', ckeditor.fields.RichTextField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='apartment.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
