# Generated by Django 5.1.7 on 2025-03-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='image_conf',
            field=models.ImageField(null=True, upload_to='pay/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatars/%Y/%m/'),
        ),
    ]
