# Generated by Django 5.1.7 on 2025-04-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_alter_apartment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m/'),
        ),
    ]
