# Generated by Django 5.1.7 on 2025-04-08 11:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_paymentaccount_bill_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='payment_proof'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
