# Generated by Django 5.1.7 on 2025-05-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_cardrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Tài khoản bị khóa'),
        ),
        migrations.AddField(
            model_name='user',
            name='lock_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
