# Generated by Django 5.1.7 on 2025-05-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_user_is_locked_user_lock_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
