# Generated by Django 5.1.7 on 2025-05-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0010_alter_payment_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('submitted', 'Đã gửi minh chứng'), ('paid', 'Đã thanh toán'), ('overdue', 'Quá hạn')], default='pending', max_length=20),
        ),
    ]
