# Generated by Django 5.1.7 on 2025-05-19 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0010_alter_payment_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
