# Generated by Django 5.1.7 on 2025-05-26 17:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_alter_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
