# Generated by Django 5.1.7 on 2025-06-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_paymentaccount_user'),
        ('apartment', '0012_locker_image'),
    ]

    operations = [
    ]
