# Generated by Django 5.1.7 on 2025-06-05 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0013_merge_0011_paymentaccount_user_0012_locker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='apartment.apartment'),
        ),
    ]
